import type { LabProject } from '@ensp-assistant/shared'

export const demoLabs: LabProject[] = [
  {
    id: 'demo-ospf-campus',
    name: 'OSPF 单区域校园网',
    path: 'demo://ospf-campus',
    topologyFile: 'demo://ospf-campus/topology.topo',
    readmeFile: 'demo://ospf-campus/README.md',
    configCount: 4,
    tags: ['OSPF', 'AR', 'S5700'],
    difficulty: 'intermediate',
    protocol: 'OSPF',
    deviceCount: 6,
    linkCount: 7,
    modifiedAt: new Date().toISOString(),
    status: 'demo',
  },
  {
    id: 'demo-vlan-trunk',
    name: 'VLAN 与 Trunk 基础实验',
    path: 'demo://vlan-trunk',
    topologyFile: 'demo://vlan-trunk/topology.topo',
    readmeFile: 'demo://vlan-trunk/README.md',
    configCount: 3,
    tags: ['VLAN', 'Trunk', 'Access'],
    difficulty: 'starter',
    protocol: 'VLAN',
    deviceCount: 5,
    linkCount: 5,
    modifiedAt: new Date().toISOString(),
    status: 'demo',
  },
  {
    id: 'demo-nat-edge',
    name: 'NAT 出口综合实验',
    path: 'demo://nat-edge',
    topologyFile: 'demo://nat-edge/topology.topo',
    readmeFile: 'demo://nat-edge/README.md',
    configCount: 5,
    tags: ['NAT', 'ACL', 'Default Route'],
    difficulty: 'advanced',
    protocol: 'NAT',
    deviceCount: 7,
    linkCount: 8,
    modifiedAt: new Date().toISOString(),
    status: 'demo',
  },
]
